### ISSUE TITLE
InfoView Cascading Issue

### ISSUE THREAD

**Issue by SimPlat** [SimPlat/Athina#7]
### Description
`InfoView` GUI content cascades due to the disappearance of `userTypePanel`s underneath the `globalInfoPanel`.

### Steps to Reproduce
Login as any user. Though results(GUI placement) vary based on user type.

### Expected Result
Upwards placement of the rest of the GUI elements upon the disappearance of another(see `MainMenuView`).

### Actual Result
GUI elements cascade to the bottom of the frame.

**Comment by skarlatosstratos** [comment]
Done
